#!/bin/sh

#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░

# Inicia sxhkd (gestor de combinaciones de teclas)
pkill sxhkd
sxhkd &
pgrep -x sxhkd >/dev/null

# Inicia update fedora
up

# Inicia picom (compositor de ventanas)
pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &
bspc config border_width 0.2

# Inicia dunst (notificaciones)
pkill dunst
dunst -conf ~/.config/dunst/dunstrc &

pkill /usr/bin/i3lock-everblush
# /usr/bin/i3lock-everblush -time 5 -locker "/usr/bin/i3lock-everblush -l" -notify 30 -notifier "notify-send 'Locker' 'Locking screen in 30 seconds'" -killtime 5 -killer "systemctl suspend" &

# Inicia Polybar
#~/.config/polybar/launch.sh &
pkill -9 polybar &
"${HOME}/.config/polybar/launch.sh"

# Configuración del fondo de pantalla
feh --bg-scale "${HOME}/.local/share/backgrounds/yoal-desurmont-yVE9sFvGssk-unsplash.jpg" &

SECOND_MONITOR_SIDE="left"
# THIRD_MONITOR_SIDE="rigth"

#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2' | awk '{print $1}')
# THIRD_MONITOR=$(xrandr | grep connected | awk '{i++}i==3' | awk '{print $1}')

Configure Monitors
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
	bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V VI
	bspc monitor $(bspc query -M | sed -n 2p) -d VII VIII IX X
	#Set Monitors Side and output
	xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL
else
	bspc monitor -d I II III IV V
fi
#bspc monitor DisplayPort-0 -d I II III IV V VI
#bspc monitor HDMI-A-0 -d VII VIII XI X

bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config pointer_follows_focus true
#
# bspc config automatic_scheme alternate
# bspc config removal_adjustment
# bspc config honor_size_hints
# bspc config ignore_ewmh_struts
#
# bspc config pointer_follows_focus false
# bspc config pointer_follows_monitor true

#Distribucion de teclado latam
setxkbmap -layout latam

# For Pycharm and Intellj
wmname LG3D

#BSPWM coloring

# bspc rule -a Gimp desktop='^2' state=floating follow=on
# bspc rule -a Chromium desktop='^7'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Rofi focus=on
# bspc rule -a Screenkey manage=off
# # bspc rule -a kitty desktop='^1'
# bspc rule -a Firefox desktop='^7'
# bspc rule -a Ardour desktop='^8'
# bspc rule -a Evince desktop='^2'
# bspc rule -a TelegramDesktop desktop='^2'

# Configuración de variables de entorno
# export SUDO_ASKPASS="$HOME/.local/bin/scripts/pass"
# export PATH="${PATH}:$HOME/.local/bin/scripts"
# export PATH="$PATH:$("$HOME/.local/bin/modulos/" | cut -f2 | paste -sd ':' -)"
# export EDITOR=nvim

# Inicia el administrador de energía de XFCE
xfce4-power-manager &

# Configura el cursor
xsetroot -cursor_name left_ptr &

# Habilita el doble toque del Touchpad
xinput set-prop "FTCS1000:00 2808:0101 Touchpad" "libinput Tapping Enabled" 1

# Configuración de monitores
# vmware-user-suid-wrapper &
# bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI-A-1 -d XI XII XIII XIV XV XVI XVII XVIII XIX XX

# Reglas para aplicaciones específicas
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# CURRENT_BORDER='2.5'
CURRENT_GAP='12'
CURRENT_SRATIO='1.4'

#bspc config border_width         2
#bspc config window_gap          12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"
bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
